### ISSUE TITLE
Property appears multiple times in data catalog

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#585] opened 2017-10-20 13:30 UTC
Each property in LoginUniqueCountByGradeShape appears four times but should only appear once.

**Comment by zednis** [comment] 2018-01-02 22:35
Is this issue found in the data catalog generated from https://bitbucket.pearson.com/projects/METIS/repos/metis-mypedia ?

To generate the data catalog HTML containing the duplicate properties for LoginUniqueCountByGradeShape what command will I need to run?

**Comment by zednis** [comment] 2018-01-02 22:48
Here is a screenshot of the issue.

![screen shot 2018-01-02 at 3 47 48 pm](https://user-images.githubusercontent.com/1057295/34503205-668ba7cc-efd4-11e7-86f4-2d74ab1ac022.png)

**Comment by zednis** [comment] 2018-01-03 16:33
I am attempting to create a unit test in ``konig-data-catalog`` to build a shape page based on a SHACL file.

I added the following test resource and unit test

src/test/resources/ShapePageTest/testShape2.ttl shape causing duplicate properties in OP)
```
@prefix alias: <http://schema.pearson.com/ns/alias/> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix fact: <http://schema.pearson.com/ns/fact/> .
@prefix konig: <http://www.konig.io/ns/core/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix reg: <https://schema.pearson.com/ns/registrar/> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix shape: <http://schema.pearson.com/shapes/> .
@prefix xas: <http://schema.pearson.com/ns/activity/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

shape: a owl:Ontology .

shape:LoginUniqueCountByGradeShape a sh:Shape ;
	prov:wasGeneratedBy <http://www.konig.io/activity/ZiYcTI0q5KYAAAFguQz8hA> ;
	sh:targetClass fact:LoginUniqueCountByGrade ;
	konig:aggregationOf xas:CreateLicenseKey ;
	konig:mediaTypeBaseName "application/vnd.pearson.loginuniquecountbygrade" ;
	sh:property  [
		sh:path konig:uniqueCount ;
		sh:datatype xsd:int ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
		konig:stereotype konig:measure
	 ]  ,  [
		sh:path alias:grade ;
		sh:class reg:SchoolGrade ;
		sh:nodeKind sh:IRI ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
		konig:stereotype konig:dimension
	 ]  ,  [
		sh:path alias:school ;
		sh:class schema:School ;
		sh:nodeKind sh:IRI ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
		konig:stereotype konig:attribute
	 ]  ,  [
		sh:path alias:city ;
		sh:class schema:City ;
		sh:nodeKind sh:IRI ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
		konig:stereotype konig:attribute
	 ]  ,  [
		sh:path alias:country ;
		sh:class schema:Country ;
		sh:nodeKind sh:IRI ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
		konig:stereotype konig:attribute
	 ]  ,  [
		sh:path konig:timeInterval ;
		sh:shape shape:DayWeekMonthYearTimeIntervalShape ;
		sh:minCount 1 ;
		sh:maxCount 1 ;
		konig:stereotype konig:dimension ]  .

<http://www.konig.io/activity/ZiYcTI0q5KYAAAFguQz8hA> a konig:LoadModelFromSpreadsheet ;
	as:endTime "2018-01-02T15:45:24.407-07:00"^^xsd:dateTime .
```
unit test:
```
	@Test
	public void testShape() throws Exception {

		load("src/test/resources/ShapePageTest");
		URI ontologyId = uri("http://example.com/ns/shapes/");

		DataCatalogBuildRequest request = new DataCatalogBuildRequest();
		request.setExampleDir(exampleDir);
		request.setGraph(graph);
		request.setOntologyId(ontologyId);
		request.setOutDir(outDir);
		request.setShapeManager(shapeManager);
		builder.build(request);
	}
```

error message: 
```
Running io.konig.datacatalog.DataCatalogBuilderTest
/Users/uzednst/Projects/konig/konig/konig-data-catalog/src/test/resources/DataCatalogBuilderTest/hierarchicalNames
/Users/uzednst/Projects/konig/konig/konig-data-catalog/src/test/resources/ShapePageTest
WARN  ShapePage - sh:targetClass not defined for shape <http://schema.pearson.com/shapes/DayWeekMonthYearTimeIntervalShape>
WARN  ShapePage - sh:targetClass not defined for shape <http://example.com/shapes/PersonShape>
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.452 sec <<< FAILURE!
testShape(io.konig.datacatalog.DataCatalogBuilderTest)  Time elapsed: 0.139 sec  <<< ERROR!
io.konig.datacatalog.DataCatalogException: Ontology not found: http://example.com/ns/shapes/
        at io.konig.datacatalog.DataCatalogUtil.ontologyList(DataCatalogUtil.java:133)
        at io.konig.datacatalog.OntologyIndexPage.render(OntologyIndexPage.java:46)
        at io.konig.datacatalog.DataCatalogBuilder.buildOntologyIndex(DataCatalogBuilder.java:254)
        at io.konig.datacatalog.DataCatalogBuilder.build(DataCatalogBuilder.java:122)
        at io.konig.datacatalog.DataCatalogBuilderTest.testShape(DataCatalogBuilderTest.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

@gmcfall 

questions:

1) Am I going about the right way to test HTML page generation for a SHACL shape?

2) Is the error caused by my test not including a reference to an ontology that defines the classes and properties referenced in the shape?

3) Is it possible to generate a HTML description of a shape without setting an ontology ID on the request?

**Comment by gmcfall** [comment] 2018-01-03 18:53
1. Your approach is sensible.
2. I believe the error occurs because your Turtle file uses the `http://schema.pearson.com/shapes/` as the Ontology Id, but your test case uses `http://example.com/ns/shapes/`.  
3. You must invoke one of the following methods on the DataCatalogBuildRequest:
   a. setOntologyList
   b. setOntologyId
   c. setOntologyInclude
   d. useDefaultOntologyList

**Comment by zednis** [comment] 2018-01-03 21:17
I think I found the root of the issue, and it may not be the data catalog generation code.  The SHACL TTL files generated from the spreadsheet appears to duplicate the definition of ``shape:LoginUniqueCountByGradeShape`` in files other than shape_LoginUniqueCountByGradeShape.ttl.

The following examples are files generated from the [mypedia-v2](https://docs.google.com/spreadsheets/d/1gyhKGRpH4M3wyJFsl63eKbComSXVql41MiJQZr31G4s/edit?usp=sharing) spreadsheet.

This is the contents of the file generated for ``shape:LoginUniqueCountBySchoolShape``.  It includes a basic shape definition for ``shape:LoginUniqueCountBySchoolShape`` and the full definition of ``shape:LoginUniqueCountByGradeShape``.

@gmcfall is the ``shape:LoginUniqueCountByGradeShape`` shape included in this definition because ``shape:LoginUniqueCountBySchoolShape`` is marked as an aggregation of ``shape:LoginUniqueCountByGradeShape`` in the spreadsheet?

shape_LoginUniqueCountBySchoolShape.ttl
```
@prefix alias: <http://schema.pearson.com/ns/alias/> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix fact: <http://schema.pearson.com/ns/fact/> .
@prefix konig: <http://www.konig.io/ns/core/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix reg: <https://schema.pearson.com/ns/registrar/> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix shape: <http://schema.pearson.com/shapes/> .
@prefix xas: <http://schema.pearson.com/ns/activity/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

shape:LoginUniqueCountBySchoolShape a sh:Shape ; 
	prov:wasGeneratedBy <http://www.konig.io/activity/ZiYcTI0q5KYAAAFguQz8hA> ; 
	sh:targetClass fact:LoginUniqueCountBySchool ; 
	konig:aggregationOf shape:LoginUniqueCountByGradeShape ; 
	konig:rollUpBy alias:school ; 
	konig:mediaTypeBaseName "application/vnd.pearson.loginuniquecountbyschool" . 

<http://www.konig.io/activity/ZiYcTI0q5KYAAAFguQz8hA> a konig:LoadModelFromSpreadsheet ; 
	as:endTime "2018-01-02T15:45:24.407-07:00"^^xsd:dateTime . 

shape:LoginUniqueCountByGradeShape a sh:Shape ; 
	prov:wasGeneratedBy <http://www.konig.io/activity/ZiYcTI0q5KYAAAFguQz8hA> ; 
	sh:targetClass fact:LoginUniqueCountByGrade ; 
	konig:aggregationOf xas:CreateLicenseKey ; 
	konig:mediaTypeBaseName "application/vnd.pearson.loginuniquecountbygrade" ; 
	sh:property  [ 
		sh:path konig:uniqueCount ; 
		sh:datatype xsd:int ; 
		sh:minCount 1 ; 
		sh:maxCount 1 ; 
		konig:stereotype konig:measure
	 ]  ,  [ 
		sh:path alias:grade ; 
		sh:class reg:SchoolGrade ; 
		sh:nodeKind sh:IRI ; 
		sh:minCount 1 ; 
		sh:maxCount 1 ; 
		konig:stereotype konig:dimension
	 ]  ,  [ 
		sh:path alias:school ; 
		sh:class schema:School ; 
		sh:nodeKind sh:IRI ; 
		sh:minCount 1 ; 
		sh:maxCount 1 ; 
		konig:stereotype konig:attribute
	 ]  ,  [ 
		sh:path alias:city ; 
		sh:class schema:City ; 
		sh:nodeKind sh:IRI ; 
		sh:minCount 1 ; 
		sh:maxCount 1 ; 
		konig:stereotype konig:attribute
	 ]  ,  [ 
		sh:path alias:country ; 
		sh:class schema:Country ; 
		sh:nodeKind sh:IRI ; 
		sh:minCount 1 ; 
		sh:maxCount 1 ; 
		konig:stereotype konig:attribute
	 ]  ,  [ 
		sh:path konig:timeInterval ; 
		sh:shape shape:DayWeekMonthYearTimeIntervalShape ; 
		sh:minCount 1 ; 
		sh:maxCount 1 ; 
		konig:stereotype konig:dimension ]  . 
```

**Closed** 2018-01-03 21:42 UTC
Labels: in progress
