### ISSUE TITLE
Sum of count across the dimension

### ISSUE THREAD

**Issue by Uvashriamm** [konigio/konig#557] opened 2017-09-27 12:43 UTC
I have a metric to compute the measure for the dimensions, But also I want to compute the measure for all the values of the dimension

For eg. I want to get the unique count students of the grades across the all the schools

**Comment by gmcfall** [comment] 2017-11-17 13:33
Can you clarify the example.  I think you mean the following:

> I want to get the number of students at a given grade level across all schools in some geographical region (city, state, country, etc.)

Is this correct?

**Comment by gmcfall** [comment] 2017-11-30 14:53
This is a duplicate of #556

**Closed by gmcfall** 2017-11-30 14:53 UTC
Labels: to do
